# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NelsonMandala_app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NelsonMandala_app
  pod 'XMSegmentedControl'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'ScaledVisibleCellsCollectionView'
  pod 'Haneke', '~> 1.0'
  pod 'HGCircularSlider', '~> 2.0.0'

end

 post_install do |installer|
     installer.generated_projects.each do |project|
           project.targets.each do |target|
               target.build_configurations.each do |config|
                   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                end
           end
    end
 end
